# Generated by Django 3.2.7 on 2022-09-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egilea', models.CharField(max_length=20)),
                ('izena', models.CharField(max_length=50)),
                ('deskribapen', models.TextField()),
            ],
        ),
    ]
